# Generated by Django 3.1.1 on 2020-09-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('other_name', models.CharField(max_length=200, verbose_name='Отчество')),
            ],
            options={
                'verbose_name': 'Пользователь',
            },
        ),
        migrations.DeleteModel(
            name='Persone',
        ),
    ]
